# Generated by Django 4.1.6 on 2023-02-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_album_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='titre',
            name='descp',
            field=models.TextField(blank=True),
        ),
    ]
