# Generated by Django 4.1.6 on 2023-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_titre_descp'),
    ]

    operations = [
        migrations.AddField(
            model_name='titre',
            name='feat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
