# Generated by Django 4.1.6 on 2023-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_titre_feat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_single', models.CharField(max_length=100)),
                ('pochette_single', models.FileField(help_text='pochette du single', upload_to='pochette_single')),
            ],
        ),
    ]
