# Generated by Django 4.1.6 on 2023-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='pochette_single',
            field=models.FileField(blank=True, help_text='pochette du single', upload_to='pochette_single'),
        ),
    ]
